# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=$(DEPLOYMENT_TOKEN);]$($(API_TOKEN_SECRET))"'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: 'dist'
    skip_app_build: true
    skip_api_build: true
    azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)
