# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- task: AzureStaticWebApp@0
  inputs:
    output_location: '/'
    skip_app_build: true
    skip_api_build: true
    azure_static_web_apps_api_token: '7329dc0d18b98eb7e2891444e6c2fbb2660b58d9ef0b9561397e6b56df7205572-94b08102-a7e3-483b-be10-c5184e21a436003216949'
