trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  DEPLOYMENT_TOKEN: $(API_TOKEN_SECRET)

steps:

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  


- task: AzureStaticWebApp@0
  inputs:
    app_location: './dist'
    output_location: 'dist'
    skip_app_build: true
    skip_api_build: true
    azure_static_web_apps_api_token: '$(DEPLOYMENT_TOKEN)'
